### ISSUE TITLE
Please make this an official Homebrew formula

### ISSUE THREAD

**Issue by leonklingele** [golangci/homebrew-tap#1]
Why not make this an official formula in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core)?
I prefer not having to use third party taps.

If it's because of automated releases, using `brew bump-formula-pr` makes it super easy to bump an official formula.

**Comment by SVilgelm** [comment]
The problem with an official formulas, that they should be delivered as a source code and compiled on a target machine, like your laptop/pc. So it requires a go installed.
Maybe it's possible to put it into a cask repo, but they have some requirements of popularity of this tap

**Comment by cblecker** [comment]
@SVilgelm this isn't correct for official formulae. You can have go as only a build time dependency, and then the binary delivered in the bottle doesn't require go

**Comment by SVilgelm** [comment]
@cblecker we have a thread for the discussion about this issue: https://github.com/orgs/golangci/teams/team/discussions/2
Let use it

**Comment by billinghamj** [comment]
Poking this one again - the page you've linked is not accessible to people who aren't members of the golangci org

**Comment by SVilgelm** [comment]
The official formulae has been added to the main homebrew tap: https://formulae.brew.sh/formula/golangci-lint

**Comment by leonklingele** [comment]
Hey, that's awesome! 🐳
