### ISSUE TITLE
Update to v1.19.1

### ISSUE THREAD

**Issue by davidlanouette** [golangci/homebrew-tap#3]
Now that v1.19.1 is out, can we get the brew formula updated to install it, instead of 1.19.0?

I've looked at the formula, and it looks like you do this using `GoReleaser`.  I'm not familiar with that tool, otherwise I'd submit a PR with the changes.

Thanks for the great tool.

**Comment by jirfag** [comment]
hi, already updated to `v1.20.0`, sorry

**Comment by davidlanouette** [comment]
👍 I saw that a few days after.  Sorry I forgot to close this issue.

Thanks for the great tool.
