### ISSUE TITLE
Version is not updated to the newest v1.24.0

### ISSUE THREAD

**Issue by programmer04** [golangci/homebrew-tap#7]
Howdy @jirfag! As in title @goreleaserbot has not updated the homebrew formula to the newest version. Is it a temporary issue? Should I update it manually in repo via PR to fix it?

**Comment by joaosa** [comment]
I noticed you seem to be updating the versions automatically. Is @goreleaserbot broken? :)

**Comment by StevenACoffman** [comment]
@ernado or another maintainer just need to run `goreleaser` locally in the [golangci/golangci-lint](https://github.com/golangci/) repo and it will make a commit here in this  [https://github.com/golangci/homebrew-tap](https://github.com/golangci/homebrew-tap) repository. It is easiest to make a new point release, so these are the steps:

1. [Install goreleaser]() e.g. `brew install goreleaser/tap/goreleaser`
2. You’ll need to export either a `GITHUB_TOKEN` environment variable, which should contain a valid GitHub token with the `repo` scope. It will be used to deploy releases to [your GitHub repository](https://github.com/golangci/homebrew-tap). You can create a token [here](https://github.com/settings/tokens/new) for GitHub.
```
$ export GITHUB_TOKEN='YOUR_GH_TOKEN'
```
3. GoReleaser will use the latest Git tag of your repository. Create a tag and push it to GitHub:
```
$ git tag -a v1.24.1 -m "Brew Tap Release"
$ git push origin v1.24.1
```
4. After releasing to GitHub or GitLab, GoReleaser can generate and publish a homebrew-tap recipe into a repository that you have access to.
```
$ goreleaser release
```

goreleaserbot is [the author name that is configured to be associated with the commit](https://github.com/golangci/golangci-lint/blob/master/.goreleaser.yml#L81) in the [homebrew-tap](https://github.com/golangci/homebrew-tap) repository. It does not run automatically without a maintainer manually invoking it, unless you use the [github action](https://github.com/goreleaser/goreleaser-action) which has not been set up yet.

**Comment by ernado** [comment]
v1.25.0 is out
