### ISSUE TITLE
Please update to v1.28

### ISSUE THREAD

**Issue by SVilgelm** [golangci/homebrew-tap#8]
Could you please update the formulae to the v1.28?

**Comment by nigurr** [comment]
@jirfag can we please get this updated with v1.28.1

**Comment by SVilgelm** [comment]
Looks like the goreleaser fails, I raised a pr to fix it: https://github.com/golangci/golangci-lint/pull/1215
the it should be updated automatically

**Comment by SVilgelm** [comment]
@golangci/core-team 
the release action fails[1] to update the tap repo, could you please validate that the `GITHUB_TOKEN` has write permissions for this repo?

[1] https://github.com/golangci/golangci-lint/runs/856068778?check_suite_focus=true#step:6:183

**Comment by SVilgelm** [comment]
sorry I mean the `secrets.GOLANGCI_LINT_TOKEN` token

**Comment by nigurr** [comment]
@golangci/core-team please resolve this.

**Comment by edwarnicke** [comment]
Actually... if I could ask for 1.28.3 :)

**Comment by SVilgelm** [comment]
we just need to solve the problem with the token, but @jirfag does not answer.

**Comment by edwarnicke** [comment]
@SVilgelm is @jirfag the only one with the keys?

**Comment by SVilgelm** [comment]
I'm not sure, but maybe @ernado also can check

**Comment by ernado** [comment]
I think that only **jirfag** can check as an org owner :(

**Comment by SVilgelm** [comment]
even the @golangci/team does not have permissions for this repo

**Comment by SVilgelm** [comment]
yes, I see the @golangci/core-team has admin permissions for the golangci-lint and golangci-lint-action repos, the @golangci/team has write permissions for same repos.
So without @jirfag we cannot do anything with this repo

**Comment by edwarnicke** [comment]
@SVilgelm Who has permissions for the golangci *org*?  Who ever that is should as a mechanical matter be able to add folks to this repo.  Whether they *should* I leave up to them to figure out :)

**Comment by SVilgelm** [comment]
The `v1.29.0` is available
